language: node_js
node_js:
- node
- lts/*
- '8'
- '7'
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libnss-mdns libavahi-compat-libdnssd-dev
- npm install -g typescript
cache:
  directories:
  - node_modules
before_script:
- npm install
script:
- npm test
notifications:
  email: false

jobs:
  include:
    - stage: npm release
      node_js: '8'
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "tommaso.marchionni@gmail.com"
        api_key: $NPM_TOKEN
        on:
          tags: true
          repo: tommasomarchionni/homebridge-openhab2